name: Scala and Java build

on:
  workflow_call
      
jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - spark: 3.3.0
            scala: 2.13.8
            jdk: '8'
            skipTests: '-DskipTests'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}
        cache: 'maven'
   # - run: git submodule update --init --recursive # Checkout Git submodule if necessary
    - name: TEMP out
      uses: actions/cache@v3
      with:
        path: staging
        key: staging_cache
    - env:
        SPARK_VERSION: ${{ matrix.spark }}
        SCALA_VERSION: ${{ matrix.scala }}
        SKIP_TESTS: ${{ matrix.skipTests }}
      run: mvn -q clean install -Dscala=${SCALA_VERSION:0:4} -Dspark.version=${SPARK_VERSION} ${SKIP_TESTS}
    - run: mkdir -p staging
    - run: cp core/target/sedona-*.jar staging
    - run: cp sql/target/sedona-*.jar staging
    - run: cp viz/target/sedona-*.jar staging
    - run: cp python-adapter/target/sedona-*.jar staging
    - run: cp spark-shaded/target/sedona-*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: generated-jars
        path: staging
